// <auto-generated />
namespace GiftShop1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class purchase_changeTo_PurchaseCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(purchase_changeTo_PurchaseCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201802092233408_purchase_changeTo_PurchaseCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
