// <auto-generated />
namespace GiftShop1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Products_addedFied_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Products_addedFied_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121131284_Products_addedFied_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
