// <auto-generated />
namespace GiftShop1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newTable_ProductInCart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newTable_ProductInCart));
        
        string IMigrationMetadata.Id
        {
            get { return "201802121156328_newTable_ProductInCart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
